button:
 -
  type: "click"
  name: "优惠券"
  key: "CANTEEN"
 -
  name: "实用功能"
  sub_button:
   -
    type: "view"
    name: "校&汇"
    url : "http://mp.weixin.qq.com/mp/homepage?__biz=MjM5NzIwOTM2Nw==&hid=1&sn=ac1b065a194920f3cafa5b361a0d14b9#wechat_redirect"
   -
    type: "click"
    name: "校历安排"
    key: "CALENDER"
   -
    type: "click"
    name: "校车摆渡车"
    key: "SHCOOLBUS"
 -
  name: "权心权意"
  sub_button:
   -
    type: "view"
    name: "权益调查"
    url: "http://mp.weixin.qq.com/mp/homepage?__biz=MjM5NzIwOTM2Nw==&hid=3&sn=9fa6c6ea30cef2c7011094bad6de1499#wechat_redirect"
   -
    type: "view"
    name: "权益日志"
    url: "http://mp.weixin.qq.com/mp/homepage?__biz=MjM5NzIwOTM2Nw==&hid=2&sn=c6989be293cb4b9f71040d41e8254cbe#wechat_redirect"
